In [1]:
import scipy as sc
import numpy as np
array1 = np.array ([(1,2,3)])
print(array1)

[[1 2 3]]


In [2]:
array2=np.linspace (0,10,5)
print(array2,'\n')
array22=np.linspace(0,1,3)
print(array22, '\n')

[ 0.   2.5  5.   7.5 10. ] 

[0.  0.5 1. ] 



In [3]:
array3=np.arange(0,10,1)
print(array3,'\n')
array4=np.arange(0,5,0.5)
print(array4,'\n')
array44=np.arange(5)
print(array44,'\n')
print(np.arange(10),'\n')

[0 1 2 3 4 5 6 7 8 9] 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[0 1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 



In [4]:
array5=np.zeros(5)
print(array5,'\n')
array6=np.ones(3)
print(array6,'\n')

[0. 0. 0. 0. 0.] 

[1. 1. 1.] 



In [5]:
array7=np.linspace(-2,3,6)
print(array7,'\n')
print(array7+2, '\n')
print(array7-1, '\n')
print(array7*3, '\n')
print(array7/2, '\n')
print(array7**4, '\n')
print((array7+2)*5, '\n')
print(np.sin(array7), '\n')
print(np.cos(array7), '\n')

[-2. -1.  0.  1.  2.  3.] 

[0. 1. 2. 3. 4. 5.] 

[-3. -2. -1.  0.  1.  2.] 

[-6. -3.  0.  3.  6.  9.] 

[-1.  -0.5  0.   0.5  1.   1.5] 

[16.  1.  0.  1. 16. 81.] 

[ 0.  5. 10. 15. 20. 25.] 

[-0.90929743 -0.84147098  0.          0.84147098  0.90929743  0.14112001] 

[-0.41614684  0.54030231  1.          0.54030231 -0.41614684 -0.9899925 ] 



In [6]:
array8= np.array ([10,20,30])
array9= np.array ([50,60,70])
result1= array8+array9
print(result1 , '\n')
print(array9-array8 , '\n')
print(array8-array9 , '\n')
print(array8*array9 , '\n')
print(array9/array8 , '\n')

[ 60  80 100] 

[40 40 40] 

[-40 -40 -40] 

[ 500 1200 2100] 

[5.         3.         2.33333333] 



In [7]:
array10=np.array([[1,2,3],[4,5,6]])
print(array10, '\n')
array11=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(array11, '\n')

[[1 2 3]
 [4 5 6]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]] 



In [8]:
array12=np.array([np.eye(3)])
print(array12, '\n')

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]] 



In [9]:
array13=np.arange(8)
print(array13 , '\n')
array14=np.reshape (array13 ,(2,4))
print(array14, '\n')
print(np.reshape(array13,(4,2)), '\n')
print(np.reshape(np.arange(8), (4,2)), '\n')
print(np.reshape(array13 , (2,5)) , '\n')

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 



ValueError: cannot reshape array of size 8 into shape (2,5)

In [10]:
array15=np.array([[1,4,5],[2,3,6]])

print(array15,'\n')
print(array15+2, '\n')
print(array15-3, '\n')
print(array15*5, '\n')
print(2/array15, '\n')
print(array15**3 , '\n')
print(np.cos(array15) , '\n')

[[1 4 5]
 [2 3 6]] 

[[3 6 7]
 [4 5 8]] 

[[-2  1  2]
 [-1  0  3]] 

[[ 5 20 25]
 [10 15 30]] 

[[2.         0.5        0.4       ]
 [1.         0.66666667 0.33333333]] 

[[  1  64 125]
 [  8  27 216]] 

[[ 0.54030231 -0.65364362  0.28366219]
 [-0.41614684 -0.9899925   0.96017029]] 



In [11]:
array16=np.array ([[1.,2.,3.],[4.,5.,6.]])
print(array16, '\n')
array17=np.array([[-1.,-2.,-3.],[-4.,-5.,-6.]])
print(array17,'\n')
print(np.dot(array16,array17), '\n')

[[1. 2. 3.]
 [4. 5. 6.]] 

[[-1. -2. -3.]
 [-4. -5. -6.]] 



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [12]:
array166=np.array([[1,2],[3,4],[5,6]])
print(array166, '\n')
print(np.dot(array16,array166), '\n')

[[1 2]
 [3 4]
 [5 6]] 

[[22. 28.]
 [49. 64.]] 



In [13]:
array18=sc.rand(8)
print(np.array(np.reshape((array18), (2,4))) ,'\n')
array19=print(np.array(np.reshape((sc.rand(8)) , (2,4))), '\n')

[[0.8977083  0.44668051 0.53495423 0.68914928]
 [0.47498842 0.35761767 0.07527342 0.6949351 ]] 

[[0.84224467 0.01262327 0.58242211 0.87440601]
 [0.7628449  0.98582222 0.25527829 0.62307027]] 



In [14]:
array20=np.array([[1,2,3] , [4,5,6], [7,8,9]])
print(array20, '\n')
print(array20[0,:], '\n')
print(array20[1,:], '\n')
print(array20[2,:], '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[4 5 6] 

[7 8 9] 



In [15]:
print(array20[:,0], '\n')
print(array20[:,1], '\n')
print(array20[:,2], '\n')

[1 4 7] 

[2 5 8] 

[3 6 9] 



In [16]:
print(array20[0,:]*array20[:,0], '\n')
print(array20[:,0]*array20[0,:], '\n')

[ 1  8 21] 

[ 1  8 21] 



In [17]:
print(np.dot((array20[0,:]),(array20[:,0])), '\n')

30 



In [18]:
print(np.dot((array20[0,:]), np.array(np.reshape(array20[:,0],(3,1)))), '\n')

[30] 



In [19]:
print(array20, '\n')
print(array20*array20, '\n')
print(np.dot(array20,array20), '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]] 



In [20]:
array21=np.arange(9).reshape((3,3))
print(array21, '\n')
array22=np.transpose(np.arange(3). reshape(1,3))
print(array22, '\n')
print(np.dot(array21, array22), '\n')
print(array21*array22, '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0]
 [1]
 [2]] 

[[ 5]
 [14]
 [23]] 

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]] 

